### PR TITLE
Fix deprecation of example_group in metadata

### PR DESCRIPTION
**Pull request by otahi**
~~Please do not merge. This pull request is work in progress.(Fri May 29 04:16:21 UTC 2015)~~
Please merge if you can accept.(Mon Jun  1 06:27:58 JST 2015)

This pull request fixes deprecation of example_group in metadata which is discussed on the issue #38.

- [X] Change code to fix deprecation of example_group in metadata
- [x] Refactor code
- [x] Check with some cases with some plugins

Please check it.

### CODE REVIEW

**Comment by ryotarai** [comment]
[Jenkins] Can one of the admins verify this patch? (say "test this please")

**Comment by otahi** [comment]
I have tested with both RSpec 2.99 and RSpec 3.X and a plugin with this fix.
https://gist.github.com/otahi/9a6fe23d7940dd8af6df

It is OK.

**Comment by ryotarai** [comment]
Awesome!! I'll test and release this PR later.

**Comment by ryotarai** [comment]
I tested and it works. Thank you.

**Comment by otahi** [comment]
Thank you for your merge and release!

**Pull request merged**
