### PR TITLE
Support basic auth

### PR DESCRIPTION
**Pull request by winebarrel**
Supports basic authentication:

```ruby
describe http('http://static.example.com/auth', basic_auth: ['dummy', 'dummy']) do
  ...
end
```

Please merge if there is no problem :pray:

### CODE REVIEW

**Comment by ryotarai** [comment]
[Jenkins] Can one of the admins verify this patch? (say "test this please")

**Comment by ryotarai** [comment]
Thank you!

**Comment by ryotarai** [comment]
v0.2.3 released.

**Comment by winebarrel** [comment]
Thanks! :+1:

**Pull request merged**
